# Generated by Django 4.2.4 on 2023-08-10 10:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='solution_content_text',
        ),
        migrations.AddField(
            model_name='problems',
            name='solution_content_richtext',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
