# Generated by Django 4.2.4 on 2023-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0002_remove_problems_solution_content_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='embeddings_json',
            field=models.JSONField(default=None),
        ),
    ]
