# Generated by Django 4.2.4 on 2023-08-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0003_problems_embeddings_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='problem_id',
            field=models.IntegerField(default=None),
        ),
    ]
