# Generated by Django 4.2.4 on 2023-08-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0007_remove_images_image_richtext_images_features_json'),
    ]

    operations = [
        migrations.RenameModel('Problems', 'Solutions'),
        migrations.RenameModel('Images', 'Images_features'),
    ]
