# Generated by Django 4.2.4 on 2023-08-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0008_auto_20230823_1047'),
    ]

    operations = [
        migrations.RenameModel('Solutions', 'Solution'),
        migrations.RenameModel('Images_features', 'Image_feature'),
    ]
