# Generated by Django 4.2.4 on 2023-08-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0011_alter_solution_is_newest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_feature',
            old_name='problems_fk',
            new_name='solution',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='problem_id',
            new_name='solution_id',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='user_fk',
            new_name='user',
        ),
    ]
