# Generated by Django 4.2.4 on 2023-08-31 15:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0012_rename_problems_fk_image_feature_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_content_richtext',
            field=ckeditor.fields.RichTextField(default='', max_length=10000),
        ),
    ]
