# Generated by Django 4.2.4 on 2023-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0013_alter_solution_solution_content_richtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='embeddings_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
